version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.8
jobs:
  build:
    docker:
      - image: 'circleci/python:3.7'
    steps:
      - checkout
      - aws-s3/sync:
          from: ./src
          to: 's3://bart.gariany.com'
          aws-region: AWS_REGION_BLUE
          overwrite: true
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
